ALTER TABLE jobs ADD COLUMN IF NOT EXISTS heartbeat_at timestamptz;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS lease_expires_at timestamptz;
ALTER TABLE agent_turns ADD COLUMN IF NOT EXISTS job_id uuid;
ALTER TABLE agent_turns ADD COLUMN IF NOT EXISTS sequence bigint GENERATED BY DEFAULT AS IDENTITY;
DO $$ BEGIN
 ALTER TABLE agent_turns ADD CONSTRAINT agent_job_ownership FOREIGN KEY(project_id,job_id) REFERENCES jobs(project_id,id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE edit_batches ADD COLUMN IF NOT EXISTS agent_turn_id uuid;
DO $$ BEGIN
 ALTER TABLE edit_batches ADD CONSTRAINT edit_agent_ownership FOREIGN KEY(project_id,agent_turn_id) REFERENCES agent_turns(project_id,id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
