import type { components } from "./generated/api-schema";
export type EditRequest = components["schemas"]["EditRequest"];
export type AgentRequest = components["schemas"]["AgentRequest"];
export type ForkRequest = components["schemas"]["ForkRequest"];
export type PublicationRequest = components["schemas"]["PublicationRequest"];
export type Transform = components["schemas"]["Transform"];
export type Representation = components["schemas"]["Representation"];
export type Observation = components["schemas"]["Observation"];
export type Entity = components["schemas"]["Entity"];
export type Camera = components["schemas"]["Camera"];
export type CoordinateFrame = components["schemas"]["CoordinateFrame"];
export type SceneDocument = components["schemas"]["SceneDocument"];
export type Revision = components["schemas"]["Revision"];
export type Branch = components["schemas"]["Branch"];
export type Project = components["schemas"]["Project"];
export type ProjectDetail = components["schemas"]["ProjectDetail"];
export type Operation = components["schemas"]["Operation"];
export type EditBatch = components["schemas"]["EditBatch"];
export type Commit = components["schemas"]["Commit"];
export type Job = components["schemas"]["Job"];
export type Asset = components["schemas"]["Asset"];
export type AssetRecord = components["schemas"]["AssetRecord"];
export type Publication = components["schemas"]["Publication"];
export type PublicationSummary = components["schemas"]["PublicationSummary"];
export type PublicationSnapshot = components["schemas"]["PublicationSnapshot"];
export type Evaluation = components["schemas"]["Evaluation"];
export type Finding = components["schemas"]["Finding"];
export type Review = components["schemas"]["Review"];
export type Policy = components["schemas"]["Policy"];
export type PolicyRevision = components["schemas"]["PolicyRevision"];
export type PolicyDetail = components["schemas"]["PolicyDetail"];
export type PolicyTemplate = components["schemas"]["PolicyTemplate"];
export type EvidenceRequest = components["schemas"]["EvidenceRequest"];
export type AgentTurn = components["schemas"]["AgentTurn"];
export type Capture = components["schemas"]["Capture"];
export type Annotation = components["schemas"]["Annotation"];
export type CreateProjectRequest = components["schemas"]["CreateProject"];
export type CreateBranchRequest = components["schemas"]["CreateBranch"];
export type Vec3 = Transform["position"];
// The selection is application state; it is not an API response.
export type Selection = {
  projectId: string;
  revisionId: string;
  entityId: string | null;
  observationId: string | null;
  cameraId: string | null;
};
